TERM_PAGES = {
    "AFRICA": ["Africa"],
    "AGENT": ["Special_agent", "Law_of_agency"],
    "AIR": ["Atmosphere_of_Earth"],
    "ALIEN": ["Alien_(law)", "Extraterrestrial_life"],
    "ALPS": ["Alps"],
    "AMAZON": ["Amazon_rainforest", "Amazons", "Amazon_River", "Amazon_(company)"],
    "AMBULANCE": ["Ambulance"],
    "AMERICA": ["United_States"],
    "ANGEL": ["Angel"],
    "ANTARCTICA": ["Antarctica"],
    "APPLE": ["Apple", "Apple_Inc."],
    "ARM": ["Arm", "Weapon"],
    "ATLANTIS": ["Atlantis"],
    "AUSTRALIA": ["Australia"],
    "AZTEC": ["Aztecs", "Aztec_Empire"],

    "BACK": ["Human_back"],
    "BALL": ["Ball"],
    "BAND": ["Concert_band", "Jazz_band", "Marching_band", "School_band", "Band_(rock_and_pop)", "Musical_ensemble", "Rubber_band"],
    "BANK": ["Bank", "Bank_(geography)"],
    "BAR": ["Bar_(establishment)", "Candy_bar", "Chocolate_bar"],
    "BARK": ["Bark_(botany)", "Bark_(sound)"],
    "BAT": ["Bat", "Baseball_bat", "Cricket_bat"],
    "BATTERY": ["Electric_battery", "Battery_(crime)", "Battery_(tort)", "Artillery_battery"],
    "BEACH": ["Beach"],
    "BEAR": ["Bear"],
    "BEAT": ["Beat_(acoustics)", "Beat_(music)"],
    "BED": ["Bed", "Bed_(geology)", "Stream_bed"],
    "BEIJING": ["Beijing"],
    "BELL": ["Bell"],
    "BELT": ["Belt_(clothing)", "Championship_belt"],
    "BERLIN": ["Berlin"],
    "BERMUDA": ["Bermuda"],
    "BERRY": ["Berry"],
    "BILL": ["Bill_Gates", "Bill_Cosby", "Bill_Clinton", "Banknote", "Bill_(law)", "Invoice", "Beak"],
    "BLOCK": ["Toy_block", "City_block", "Block_(periodic_table)", "Blockchain", "Block_(Internet)"],
    "BOARD": ["Board_game", "Blackboard", "Whiteboard", "Board_of_directors", "Sounding_board", "Cutting_board", "Plank_(wood)"],
    "BOLT": ["Bolt_(fastener)", "Bolt_(firearms)", "Bolt_(climbing)", "Usain_Bolt"],
    "BOMB": ["Bomb"],
    "BOND": ["Bond_(finance)", "Bail", "Chemical_bond", "James_Bond_(literary_character)"],
    "BOOM": ["Sonic_boom", "Baby_boom", "Explosion"],
    "BOOT": ["Boot"],
    "BOTTLE": ["Bottle"],
    "BOW": ["Bow_and_arrow", "Bowing"],
    "BOX": ["Box", "Boxing"],
    "BRIDGE": ["Bridge", "Bridge_(instrument)", "Bridge_(music)", "Bridge_(exercise)"],
    "BRUSH": ["Brush"],
    "BUCK": ["Dollar", "Deer"],
    "BUFFALO": ["Bubalina", "Bison", "Buffalo,_New_York"],
    "BUG": ["Bug_(engineering)", "Hemiptera", "Covert_listening_device"],
    "BUGLE": ["Bugle"],
    "BUTTON": ["Button", "Button_(computing)", "Push-button"],

    "CALF": ["Calf", "Calf_(leg)"],
    "CANADA": ["Canada"],
    "CAP": ["Cap", "Baseball_cap"],
    "CAPITAL": ["Capital_city", "Capital_(economics)"],
    "CAR": ["Car"],
    "CARD": ["Playing_card", "Identity_document"],
    "CARROT": ["Carrot"],
    "CASINO": ["Casino"],
    "CAST": ["Casting_(metalworking)", "Orthopedic_cast", "Casting_(performing_arts)"],
    "CAT": ["Cat"],
    "CELL": ["Electrochemical_cell", "Prison_cell", "Mobile_phone", "Cellular_network", "Cell_(biology)"],
    "CENTAUR": ["Centaur"],
    "CENTER": ["Centre_(geometry)", "Center_fielder", "City_centre"],
    "CHAIR": ["Chair", "Chairperson"],
    "CHANGE": ["Impermanence", ],
    "CHARGE": ["Charge_(physics)", "Criminal_charge", "Charge_(warfare)", "Charge_(heraldry)"],
    "CHECK": ["Check_(chess)", "Cheque"],
    "CHEST": ["Thorax", "Chest_(furniture)"],
    "CHICK": ["Bird"],
    "CHINA": ["China", "Porcelain"],
    "CHOCOLATE": ["Chocolate"],
    "CHURCH": ["Church_(building)", "Church_(congregation)", "Christian_denomination", "Church_service"],
    "CIRCLE": ["Circle"],
    "CLIFF": ["Cliff"],
    "CLOAK": ["Cloak"],
    "CLUB": ["Club_(weapon)", "Club_(organization)", "Nightclub", "Tail_club", "Sports_club", "Clubs_(suit)"],
    "CODE": ["Code", "Source_code", "Code_of_law", "Building_code"],
    "COLD": ["Cold", "Common_cold"],
    "COMIC": ["Comics", "Comedian"],
    "COMPOUND": ["Compound_(linguistics)", "Chemical_compound", "Compound_interest", "Compound_(enclosure)"],
    "CONCERT": ["Concert"],
    "CONDUCTOR": ["Conducting", "Electrical_conductor", "Conductor_(rail)"],
    "CONTRACT": ["Contract"],
    "COOK": ["Cooking", "Cook_(profession)", "Chef"],
    "COPPER": ["Copper", "Copper_(color)"],
    "COTTON": ["Cotton"],
    "COURT": ["Pitch_(sports_field)", "Food_court", "Courtyard", "Court", "Courthouse"],
    "COVER": ["Suppressive_fire", "Cover_(cricket)", "Official_cover", "Album_cover", "Book_cover"],
    "CRANE": ["Crane_(bird)", "Crane_(machine)"],
    "CRASH": ["Stock_market_crash", "Collision", "Crash_(computing)"],
    "CRICKET": ["Cricket", "Cricket_(insect)"],
    "CROSS": ["Cross", "Christian_cross"],
    "CROWN": ["Crown", "Crown_(tooth)", "Crown_(dentistry)"],

    "CYCLE": ["Cycle_(music)", "Cycle_(graph_theory)", "Bicycle"],
    "CZECH": ["Czechs", "Czech_Republic"],
    "DANCE": ["Dance"],
    "DATE": ["Calendar_date", "Dating", "Date_palm"],
    "DAY": ["Day"],
    "DEATH": ["Death"],
    "DECK": ["Deck_(bridge)", "Deck_(building)", "Deck_(ship)", "Flight_deck", "Playing_card"],
    "DEGREE": ["Degree_(angle)", "Degree_(temperature)", "Academic_degree", "Degree_(music)"],
    "DIAMOND": ["Diamonds_(suit)", "Rhombus", "Diamond_(gemstone)", "Diamond"],
    "DICE": ["Dice", "DICE_(company)"],
    "DINOSAUR": ["Dinosaur"],
    "DISEASE": ["Disease"],
    "DOCTOR": ["Doctor_(title)", "Physician"],
    "DOG": ["Dog"],
    "DRAFT": ["Draft_(sports)", "Conscription", "Draft_document"],
    "DRAGON": ["Dragon"],
    "DRESS": ["Dress"],
    "DRILL": ["Drill_(animal)", "Drill", "Fire_drill"],
    "DROP": ["Drop_(liquid)", "Drop_(unit)", "Drop_(music)"],
    "DUCK": ["Duck"],
    "DWARF": ["Midget", "Dwarf_(folklore)", "Dwarf_(Middle-earth)", "Dwarf_(Dungeons_%26_Dragons)"],

    "EAGLE": ["Eagle"],
    "EGYPT": ["Egypt"],
    "EMBASSY": ["Diplomatic_mission"],
    "ENGINE": ["Engine"],
    "ENGLAND": ["England"],
    "EUROPE": ["Europe"],
    "EYE": ["Eye"],

    "FACE": ["Face", "Face_(geometry)"],
    "FAIR": ["Fair", "Trade_fair", "Light_skin"],
    "FALL": ["Free_fall", "Autumn", "Falling_(accident)"],
    "FAN": ["Fan_(machine)", "Fan_(person)"],
    "FENCE": ["Fence"],
    "FIELD": ["Field_(agriculture)", "Pitch_(sports_field)"],
    "FIGHTER": ["Fighter_aircraft", "Warrior", "Combatant"],
    "FIGURE": ["Figurine", "Model_figure", "Shape"],
    "FILE": ["Computer_file", "Document", "File_(tool)"],
    "FILM": ["Photographic_film", "Film"],
    "FIRE": ["Structure_fire", "Fire"],
    "FISH": ["Fish", "Fish_as_food"],
    "FLUTE": ["Flute"],
    "FLY": ["Flight", "Fly"],
    "FOOT": ["Foot_(unit)", "Foot"],
    "FORCE": ["Force", "The_Force"],
    "FOREST": ["Forest"],
    "FORK": ["Intersection_(road)", "Fork_(software_development)", "Fork"],
    "FRANCE": ["France"],

    "GAME": ["Game", "Game_(hunting)"],
    "GAS": ["Gasoline", "Fuel_gas", "Gas"],
    "GENIUS": ["Genius"],
    "GERMANY": ["Germany"],
    "GHOST": ["Ghost"],
    "GIANT": ["Giant"],
    "GLASS": ["Glass", "Glasses", ""],
    "GLOVE": ["Glove"],
    "GOLD": ["Gold", "Gold_(color)"],
    "GRACE": ["Grace_(prayer)", "Divine_grace"],
    "GRASS": ["Grass"],
    "GREECE": ["Greece"],
    "GREEN": ["Green"],
    "GROUND": ["Soil", "Ground_(electricity)", "Ground_(cricket)"],

    "HAM": ["Ham"],
    "HAND": ["Hand", "Card_game"],
    "HAWK": ["Hawk"],
    "HEAD": ["Head"],
    "HEART": ["Heart_symbol", "Heart"],
    "HELICOPTER": ["Helicopter"],
    "HIMALAYAS": ["Himalayas"],
    "HOLE": ["Hole"],
    "HOLLYWOOD": ["Hollywood"],
    "HONEY": ["Honey"],
    "HOOD": ["Hood_(headgear)", "Hoodie"],
    "HOOK": ["Hook"],
    "HORN": ["Horn_(instrument)", "Horn_(anatomy)", "Horn_(acoustic)"],
    "HORSE": ["Horse"],
    "HORSESHOE": ["Horseshoe"],
    "HOSPITAL": ["Hospital"],
    "HOTEL": ["Hotel"],

    "ICE": ["Digital_ICE", "Ice"],
    "ICE CREAM": ["Ice_cream"],
    "INDIA": ["India"],
    "IRON": ["Branding_iron", "Clothes_iron", "Hair_iron", "Soldering_iron", "Iron"],
    "IVORY": ["Ivory"],
    
    "JACK": ["Jack_(device)", "Jack_the_Ripper", "Jack_(given_name)"],
    "JAM": ["Fruit_preserves", "Radio_jamming"],
    "JET": ["Jet_aircraft"],
    "JUPITER": ["Jupiter"],
    
    "KANGAROO": ["Kangaroo"],
    "KETCHUP": ["Ketchup"],
    "KEY": ["Key_(cryptography)", "Lock_and_key", "Computer_keyboard", "Key_(music)"],
    "KID": ["Goat", "Youth", "Child"],
    "KING": ["King"],
    "KIWI": ["Kiwifruit", "Kiwi_(bird)", "Kiwi_(people)"],
    "KNIFE": ["Knife"],
    "KNIGHT": ["Knight", "Knight_(chess)"],

    "LAB": ["Laboratory"],
    "LAP": ["Lap", "Race_track", "Swimming_pool"],
    "LASER": ["Laser"],
    "LAWYER": ["Lawyer"],
    "LEAD": ["Leading_actor", "Lead"],
    "LEMON": ["Lemon"],
    "LEPRECHAUN": ["Leprechaun"],
    "LIFE": ["Life", "Personal_life", "Everyday_life"],
    "LIGHT": ["Light", "Traffic_light", "Electric_light"],
    "LIMOUSINE": ["Limousine"],
    "LINE": ["Line_(geometry)", "Line_(geometry)", "Line_(formation)", "Line_of_battle", "Line_(electrical_engineering)"],
    "LINK": ["Telecommunications_link", "Link_(The_Legend_of_Zelda)", "Linked_list", "Links_(web_browser)", "Hyperlink"],
    "LION": ["Lion"],
    "LOCH NESS": ["Loch_Ness", "Loch_Ness_(disambiguation)"],
    "LOCK": ["Lock_and_key", "Lock_(water_navigation)"],
    "LOG": ["Lumber", "Firewood", "Logging", "Trunk_(botany)", "Log_file", "Logarithm"],
    "LONDON": ["London"],
    "LUCK": ["Luck"],
    
    "MAIL": ["Mail", "Chain_mail"],
    "MAMMOTH": ["Mammoth"],
    "MAPLE": ["Maple"],
    "MARBLE": ["Marble", "Marble_sculpture", "Marble_(toy)"],
    "MARCH": ["March", "Marching"],
    "MASS": ["Mass", "Mass_(liturgy)", "Mass_in_the_Catholic_Church"],
    "MATCH": ["Match"],
    "MERCURY": ["Mercury_(planet)", "Mercury_(element)", "Mercury_(mythology)", "Match"],
    "MEXICO": ["Mexico"],
    "MICROSCOPE": ["Microscope"],
    "MILLIONAIRE": ["Millionaire"],
    "MINE": ["Miner", "Mining", "Land_mine"],
    "MINT": ["Mint_(facility)", "Spearmint", "Mentha"],
    "MISSILE": ["Missile"],
    "MODEL": ["Model"],
    "MOLE": ["Mole_(unit)", "Nevus", "Mole_(animal)", "Golden_mole", "Marsupial_mole"],
    "MOON": ["Moon"],
    "MOSCOW": ["Moscow"],
    "MOUNT": ["Mountain", "Mount_(grappling)"],
    "MOUSE": ["Mickey_Mouse", "Computer_mouse", "Mouse"],
    "MOUTH": ["River_mouth", "Mouth"],
    "MUG": ["Mug", "Mug_shot"],

    "NAIL": ["Nail_(fastener)", "Nail_(anatomy)"],
    "NEEDLE": ["Knitting_needle", "Sewing_needle", "Pine", "Hypodermic_needle"],
    "NET": ["Net_(device)", "Net_(economics)", "Internet", "Net_sport"],
    "NEW YORK": ["New_York_City", "New_York_(state)"],
    "NIGHT": ["Night"],
    "NINJA": ["Ninja", "Ninja_(gamer)"],
    "NOVEL": ["Novel"],

    "OCTOPUS": ["Octopus"],
    "ORGAN": ["Organ_(biology)", "Organ_(music)"],
    
    "PANTS": ["Trousers"],
    "PAPER": ["Paper", "Term_paper"],
    "PART": ["Part_(music)", "Spare_part"],
    "PIANO": ["Piano"],
    "PIN": ["Pin", "Personal_identification_number"],
    "POUND": ["Pound_(mass)", "Pound_(force)", "Pound_(currency)"],
    "PYRAMID": ["Pyramid", "Pyramid_(geometry)", "Pyramid_scheme"],

    "RACKET": ["Racket_(sports_equipment)", "Racketeering"],
    "ROCK": ["Rock_(geology)", "Rock_music"],

    "SHADOW": ["Shadow"],
    "SNOW": ["Snow"],
    "SPY": ["Espionage", "Spy_film"],
    "SQUARE": ["Square", "Square_number", "Square,_Inc."],
    "STATE": ["State_(polity)", "State_(computer_science)"],

    "TOKYO": ["Tokyo"],
    "TRUNK": ["Trunk_(car)", "Trunk_(botany)", "Torso"],
    "TABLE": ["Table_(furniture)", "Table_(database)", "Table_(information)"]
}