TERM_PAGES = {
    "AFRICA": ["Africa"],
    "AGENT": ["Special_agent", "Law_of_agency"],
    "AIR": ["Atmosphere_of_Earth"],
    "ALIEN": ["Alien_(law)", "Extraterrestrial_life", "Alien_(film)"],
    "ALPS": ["Alps"],
    "AMAZON": ["Amazon_rainforest", "Amazons", "Amazon_River", "Amazon_(company)"],
    "AMBULANCE": ["Ambulance"],
    #"AMERICA": ["United_States"],
    "ANGEL": ["Angel"],
    "ANTARCTICA": ["Antarctica"],
    "APPLE": ["Apple", "Apple_Inc."],
    "ARM": ["Arm", "Weapon"],
    "ATLANTIS": ["Atlantis"],
    "AUSTRALIA": ["Australia"],
    "AZTEC": ["Aztecs", "Aztec_Empire"],

    "DINOSAUR": ["Dinosaur"],
    "LION": ["Lion"],
    "OCTOPUS": ["Octopus"],
    
    "CROWN": ["Crown", "Crown_(tooth)", "Crown_(dentistry)"],
    "LINK": ["Telecommunications_link", "Link_()The_Legend_of_Zelda", "Linked_list", "Links_(web_browser)", "Hyperlink"],
    "TOKYO": ["Tokyo"],
    "RACKET": ["Racket_(sports_equipment)", "Racketeering"],
    "ROCK": ["Rock_(geology)", "Rock_music"],
    "PANTS": ["Trousers"],
    "MOON": ["Moon"],
    "MAMMOTH": ["Mammoth"],
    "SHADOW": ["Shadow"],
    "PIN": ["Pin", "Personal_identification_number"],
    "NINJA": ["Ninja", "Ninja_(gamer)"],
    "POUND": ["Pound_(mass)", "Pound_(force)", "Pound_(currency)"],
    "ORGAN": ["Organ_(biology)", "Organ_(music)"],
    "PART": ["Part_(music)", "Spare_part"],
    "SNOW": ["Snow"],
    "SPY": ["Espionage", "Spy_film"],
    "PIANO": ["Piano"],
    "NOVEL": ["Novel"],
    "PAPER": ["Paper", "Term_paper"],
    "BUCK": ["Dollar", "Deer"],
    "EUROPE": ["Europe"],
    "TRUNK": ["Trunk_(car)", "Trunk_(botany)", "Torso", "Elephant"],
    "STATE": ["State_(polity)", "State_(computer_science)"],
    "BED": ["Bed", "Bed_(geology)", "Stream_bed"],
    "TABLE": ["Table_(furniture)", "Table_(database)", "Table_(information)"],

    "PYRAMID": ["Pyramid", "Pyramid_(geometry)", "Pyramid_scheme"],
    "SQUARE": ["Square", "Square_number", "Square,_Inc."],
    "CENTER": ["Centre_(geometry)", "Center_fielder", "City_centre"]
}