TERM_PAGES = {
    "AFRICA": ["Africa"],
    "AGENT": ["Special_agent", "Law_of_agency"],
    "AIR": [("Atmosphere_of_Earth", "ATMOSPHERE")],
    "ALIEN": ["Alien_(law)", "Extraterrestrial_life", "Alien_(film)"],
    "ALPS": ["Alps"],
    "AMAZON": ["Amazon_rainforest", "Amazons", "Amazon_River", "Amazon_(company)"],
    "AMBULANCE": ["Ambulance"],
    #"AMERICA": ["United_States"],
    "ANGEL": ["Angel"],
    "ANTARCTICA": ["Antarctica"],
    "APPLE": ["Apple", "Apple_Inc."],
    "ARM": ["Arm", ("Weapon", "WEAPON")],
    "ATLANTIS": ["Atlantis"],
    "AUSTRALIA": ["Australia"],
    "AZTEC": ["Aztecs", "Aztec_Empire"],

    "BACK": ["Human_back"],
    "BALL": ["Ball"],
    "BAND": ["Concert_band", "Jazz_band", "Marching_band", "School_band", "Band_(rock_and_pop)", "Musical_ensemble", "Rubber_band"],
    "BANK": ["Bank", "Bank_(geography)"],
    "BAR": ["Bar_(establishment)", "Candy_bar", "Chocolate_bar"],
    "BARK": ["Bark_(botany)", "Bark_(sound)"],
    "BAT": ["Bat", "Baseball_bat", "Cricket_bat"],
    "BATTERY": ["Electric_battery", "Battery_(crime)", "Battery_(tort)", "Artillery_battery"],
    "BEACH": ["Beach"],
    "BEAR": ["Bear"],
    "BEAT": ["Strike_(attack)", "Beat_(acoustics)", "Beat_(music)"],
    "BED": ["Bed", "Bed_(geology)", "Stream_bed"],
    "BEIJING": ["Beijing"],
    "BELL": ["Bell"],
    "BELT": ["Belt_(clothing)", "Championship_belt"],
    "BERLIN": ["Berlin"],
    "BERMUDA": ["Bermuda"],
    "BERRY": ["Berry"],
    "BILL": ["Bill_Gates", "Bill_Cosby", "Bill_Clinton", "Banknote", "Bill_(law)", ("Invoice", "INVOICE"), ("Beak", "BEAK")],
    "BLOCK": ["Toy_block", "City_block", "Block_(periodic_table)", "Blockchain", "Block_(Internet)"],
    "BOARD": ["Board_game", "Blackboard", "Whiteboard", "Board_of_directors", "Sounding_board", "Cutting_board", ("Plank_(wood)", "PLANK")],
    "BOLT": ["Bolt_(fastener)", "Bolt_(firearms)", "Bolt_(climbing)", "Usain_Bolt"],
    "BOMB": ["Bomb"],
    "BOND": ["Bond_(finance)", ("Bail", "BAIL"), "Chemical_bond", "James_Bond_(literary_character)"],
    "BOOM": ["Sonic_boom", "Baby_boom"],
    "BOOT": ["Boot"],
    "BOTTLE": ["Bottle"],
    "BOW": ["Bow_and_arrow", "Bowing"],
    "BOX": ["Box", "Boxing"],
    "BRIDGE": ["Bridge", "Bridge_(instrument)", "Bridge_(music)", "Bridge_(exercise)"],
    "BRUSH": ["Brush"],
    "BUCK": [("Dollar", "DOLLAR"), ("Deer", "DEER")],
    "BUFFALO": [("Bubalina", "BUBALINA"), ("Bison", "BISON"), "Buffalo,_New_York"],
    "BUG": ["Bug_(engineering)", ("Hemiptera", "Hemiptera"), "Covert_listening_device"],
    "BUGLE": ["Bugle"],
    "BUTTON": ["Button", "Button_(computing)", "Push-button"],

    "CALF": ["Calf", "Calf_(leg)"],
    "CANADA": ["Canada"],
    "CENTER": ["Centre_(geometry)", "Center_fielder", "City_centre"],
    "CROWN": ["Crown", "Crown_(tooth)", "Crown_(dentistry)"],

    "DINOSAUR": ["Dinosaur"],

    "EUROPE": ["Europe"],

    "LINK": ["Telecommunications_link", "Link_(The_Legend_of_Zelda)", "Linked_list", "Links_(web_browser)", "Hyperlink"],
    "LION": ["Lion"],

    "MAMMOTH": ["Mammoth"],
    "MOON": ["Moon"],

    "NINJA": ["Ninja", "Ninja_(gamer)"],
    "NOVEL": ["Novel"],

    "OCTOPUS": ["Octopus"],
    "ORGAN": ["Organ_(biology)", "Organ_(music)"],
    
    "PANTS": [("Trousers", "TROUSER")],
    "PAPER": ["Paper", "Term_paper"],
    "PART": ["Part_(music)", "Spare_part"],
    "PIANO": ["Piano"],
    "PIN": ["Pin", "Personal_identification_number"],
    "POUND": ["Pound_(mass)", "Pound_(force)", "Pound_(currency)"],
    "PYRAMID": ["Pyramid", "Pyramid_(geometry)", "Pyramid_scheme"],

    "RACKET": ["Racket_(sports_equipment)", "Racketeering"],
    "ROCK": ["Rock_(geology)", "Rock_music"],

    "SHADOW": ["Shadow"],
    "SNOW": ["Snow"],
    "SPY": [("Espionage", "ESPIONAGE"), "Spy_film"],
    "SQUARE": ["Square", "Square_number", "Square,_Inc."],
    "STATE": ["State_(polity)", "State_(computer_science)"],

    "TOKYO": ["Tokyo"],
    "TRUNK": ["Trunk_(car)", "Trunk_(botany)", ("Torso", "TORSO"), "Elephant"],
    "TABLE": ["Table_(furniture)", "Table_(database)", "Table_(information)"]
}